name: Build & Lint

on:
  push:
    branches: [main]

env:
  node-version: "18"
  path: "dist" # The directory where your assets are generated, should match build.mjs

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
  
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
  
      - name: Install Dependencies
        run: yarn install --immutable
  
      - name: Build
        run: yarn run build
  
      - name: Push to Release
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: ${{ env.path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
          SKIP_EMPTY_COMMITS: true
